changelog = true
classOrder = [
    "Constructor",
    "DataStore",
    "Proxy",
    "Signal",
    "TaskManager"
]

[home]
enabled = true
includeReadme = false # Optional

[[home.features]]
title = "Easy to use"
description = "This module is very easy to use. Giving you direct access to values and easy to learn module. With a built in auto save you don't have to worry manually having to have to save."

[[home.features]]
title = "Compression"
description = "Data can be compressed to lower the character count in data, allowing larger sized data to be saved. The module gives various settings to play around with to compress data."

[[home.features]]
title = "Queuing"
description = "Queing is usefull because you can save data without opening the data store iteself. Giving you different ways to do so."

[docusaurus]
tagline = "Easy to use Data Store Module for Roblox"
favicon = "/ICON.ico"
projectName = "Suphi's Data Store Module"

[[navbar.items]]
href = "https://discord.gg/suphi-kaner-909926338801061961"
label = "Discord"
position = "right"

[[navbar.items]]
href = "https://create.roblox.com/marketplace/asset/11671168253"
label = "Roblox"
position = "right"

